### ISSUE TITLE
LPM KODI addon - About Signs and Songs

### ISSUE THREAD

**Issue by rockrider69** [rockrider69/service.LanguagePreferenceManager#2]
@knappeGEIL  -  Hope it can be a way to contact you without bothering ...
Hello !
a couple of months ago I started to create my own version of LPM and have developped it a bit since then.
Recently vis the KODI forum I got a request to develop some kind of filter to ignore Signs and Songs types of subtitles. I developped something with is working ok, but soon after I discovered your own fork.
You have done the same in a more elegant way so I was wondering if I could reuse your idea based on Keywords Blacklisting.
Hope this message will find you in a way or another :)
Regards

**Comment by KnappeGEIL** [comment]
Hi @rockrider69,

sure thing, just use what you need. 😃 

Best regards

**Comment by rockrider69** [comment]
Thanks a lot for the prompt answer @KnappeGEIL, that is great and highly appreciated !
Best Regards
