### ISSUE TITLE
On each play, after 2 seconds, play freeze and jump to the beginning.

### ISSUE THREAD

**Issue by SubEdict** [rockrider69/service.LanguagePreferenceManager#8]
Hi @rockrider69 

Up until now, everything worked perfectly but the latest update (1.0.2) started this issue that everything started playing twice in the first 2 seconds.
I had to neutralize the addon just to play normally without the 2-second jump-back issue.

Only use it for the "first and second language" choice, found it very useful for me.
Installing the latest zip didn't help.

**Comment by rockrider69** [comment]
Hello,
thanks a lot for reporting that I will have to investigate more.
Indeed 1.0.2 adds a quick jumpback to workaround a kodi bug not displaying very first subs.
But at least on my Kodi setup it is not noticeable at all, no video freeze or audio glitch.

Can you tell me what your Kodi box/hardware is exactly?
And best is if you have time to activate debug level **on both Kodi and LPM**, reproduce the bug , and then attach a link to your kodi log here.
Thanks

**Comment by rockrider69** [comment]
@SubEdict .... And while I am investigating this, if you want to downgrade to a previous version, please install the v1.0.0 release available at my github.

**Comment by SubEdict** [comment]
PC, Win-10/7 x64, Kodi 20.2 + Nightly: 20231120-0f4ed673-Nexus-x64.exe
>...it is not noticeable at all, no video freeze or audio glitch.

Almost not noticeable ...I mean it's all happens in 1 second, and yes most of the time it's just a quick jumpback.

Thanks for the fast reply and the confirmation, no rush, it is still great, will downgrade in the meantime.

**Comment by rockrider69** [comment]
"Almost", you are right of course ;)

One more question, did you say you only use it for first and second AUDIO language ? meaning not for subtitles...
asking that because it made me think I could very well skip the jumpback when no subtitles at selected at all.
That would make sense to restrict the workaround then, because the latency is only on subs not audio.
I might do it in any case...

**Comment by SubEdict** [comment]
Nope, only to auto-activate the second subtitle "English" when my default language is not embedded in the file.
I don't use any other settings like audio track etc.

**Comment by rockrider69** [comment]
@SubEdict
please check on 1.0.3BETA6 version proposed. Among several other fixes or new features it includes :
 
- New option to control Fast Subtitles Display -aka workaround 10sec subs latency-
          3 choices : Disabled, Start Only, Start+Resume. Default is Disabled.

Using Disabled you should get same behaviour as 1.0.1 version, no jumpback at all.

**Comment by SubEdict** [comment]
We're back to business, smooth start without any delay, works great (default).
Thanks a lot. 👏

**Comment by rockrider69** [comment]
Thanks for confirming !
 I close now the issue. I will soon push this new version 1.0.3 to Kodi Repository.

**Comment by rockrider69** [comment]
Thanks for confirming !
 I close now the issue. I will soon push this new version 1.0.3 to Kodi Repository.
